// colors for terminal
#define VGA_COLOR_BLACK 0x00
#define VGA_COLOR_BLUE 0x01
#define VGA_COLOR_GREEN 0x02
#define	VGA_COLOR_CYAN 0x03
#define VGA_COLOR_RED 0x04
#define VGA_COLOR_MAGENTA 0x05
#define VGA_COLOR_BROWN 0x06
#define VGA_COLOR_LIGHT_GREY 0x07
#define VGA_COLOR_DARK_GREY 0x08
#define VGA_COLOR_LIGHT_BLUE 0x09
#define VGA_COLOR_LIGHT_GREEN 0x0a
#define VGA_COLOR_LIGHT_CYAN 0x0b
#define VGA_COLOR_LIGHT_RED 0x0c
#define VGA_COLOR_LIGHT_MAGENTA 0x0d
#define VGA_COLOR_LIGHT_BROWN 0x0e
#define	VGA_COLOR_WHITE 0x0f
